print("Wie heißen Sie?", end=' ')
name = input()
print("Weiblich oder Mannlich?", end=' ')
genus = input()
print("Wie alt sind Sie?", end=' ')
alter = input()
print("Was sind Sie von Beruf?", end=' ')
beruf = input()

print(f"Okay, Sie sind {name}, {genus}, {alter} alt und {beruf} von Beruf.")
